"""Base Strategy for BDD Generation

Abstract base class and data structures for multi-strategy BDD test generation.

This module provides the foundation for the Fishnet v2.0.0 strategy pattern,
enabling pluggable BDD generation strategies from PM behavior specifications.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List


@dataclass
class BehaviorSpec:
    """Extracted behavior specification from PM documentation
    
    Represents a single PM behavior/tool that needs BDD test coverage.
    """
    name: str
    description: str
    capability_level: str  # Apprentice, Journeyman, Master, Expert
    knowledge_scope: str   # Pond, Lake, Sea, Ocean
    input_schema: Dict[str, Any]
    output_schema: Dict[str, Any]
    mutates_kg: bool
    concurrency_safe: bool
    ontology_mapping: str  # e.g., "nusy:PMBehavior-CreateFeature"
    cli_example: str
    sparql_query: str = ""
    source_file: str = ""
    behavior_id: str = ""


@dataclass
class BDDScenario:
    """Generated BDD scenario (Given-When-Then)
    
    Represents a single test scenario within a feature file.
    """
    scenario_name: str
    scenario_type: str  # happy_path, edge_case, error_handling
    given_steps: List[str]
    when_steps: List[str]
    then_steps: List[str]
    strategy_used: str  # Which strategy generated this scenario
    tags: List[str] = field(default_factory=list)


@dataclass
class BDDFeatureFile:
    """Complete .feature file with multiple scenarios
    
    Represents a Gherkin feature file with background and scenarios.
    """
    feature_name: str
    feature_description: str
    background_steps: List[str]
    scenarios: List[BDDScenario]
    tags: List[str]
    behavior_spec: BehaviorSpec
    
    def to_gherkin(self) -> str:
        """Convert to Gherkin format"""
        lines = []
        
        # Provenance comment
        lines.append(f"# Generated by Fishnet v2.0.0")
        lines.append(f"# Strategy: {self.scenarios[0].strategy_used if self.scenarios else 'Unknown'}")
        lines.append(f"# Source: {self.behavior_spec.source_file}")
        lines.append(f"# Behavior: {self.behavior_spec.name}")
        lines.append("")
        
        # Tags
        if self.tags:
            lines.append("@" + " @".join(self.tags))
        
        # Feature header
        lines.append(f"Feature: {self.feature_name}")
        lines.append(f"  {self.feature_description}")
        lines.append("")
        
        # Background
        if self.background_steps:
            lines.append("  Background:")
            for step in self.background_steps:
                lines.append(f"    {step}")
            lines.append("")
        
        # Scenarios
        for scenario in self.scenarios:
            if scenario.tags:
                lines.append("  @" + " @".join(scenario.tags))
            lines.append(f"  Scenario: {scenario.scenario_name}")
            
            for step in scenario.given_steps:
                lines.append(f"    Given {step}")
            for step in scenario.when_steps:
                lines.append(f"    When {step}")
            for step in scenario.then_steps:
                lines.append(f"    Then {step}")
            lines.append("")
        
        return "\n".join(lines)


class BDDGenerationStrategy(ABC):
    """Abstract base for BDD generation strategies
    
    Each strategy implements a different approach to generating BDD scenarios
    from behavior specifications.
    """
    
    @property
    @abstractmethod
    def strategy_name(self) -> str:
        """Strategy identifier (e.g., 'BottomUp', 'TopDown')"""
        pass
    
    @abstractmethod
    def generate_scenarios(
        self, 
        behavior: BehaviorSpec,
        context: Dict[str, Any] = None
    ) -> List[BDDScenario]:
        """Generate 3 scenarios (happy, edge, error) for a behavior
        
        Args:
            behavior: Extracted behavior specification
            context: Additional context (ontology, examples, etc.)
            
        Returns:
            List of 3 BDDScenario objects
        """
        pass
    
    def generate_feature_file(
        self,
        behavior: BehaviorSpec,
        context: Dict[str, Any] = None
    ) -> BDDFeatureFile:
        """Generate complete .feature file for a behavior
        
        Calls generate_scenarios() and wraps in feature structure.
        
        Args:
            behavior: Extracted behavior specification
            context: Additional context
            
        Returns:
            BDDFeatureFile ready to write to disk
        """
        scenarios = self.generate_scenarios(behavior, context)
        return BDDFeatureFile(
            feature_name=f"MCP Tool: {behavior.name}",
            feature_description=behavior.description,
            background_steps=self._generate_background(behavior),
            scenarios=scenarios,
            tags=[
                f"{behavior.capability_level.lower()}",
                f"{behavior.knowledge_scope.lower()}",
                behavior.name
            ],
            behavior_spec=behavior
        )
    
    @abstractmethod
    def _generate_background(self, behavior: BehaviorSpec) -> List[str]:
        """Generate Background section (common setup steps)
        
        Args:
            behavior: Behavior specification
            
        Returns:
            List of Given steps for Background section
        """
        pass
