"""Unit tests for Fishnet BDD generation strategies"""

import pytest
from nusy_orchestrator.santiago_builder.fishnet_strategies.base_strategy import (
    BehaviorSpec,
    BDDScenario,
    BDDFeatureFile,
)
from nusy_orchestrator.santiago_builder.fishnet_strategies.bottom_up_strategy import (
    BottomUpStrategy,
)


@pytest.fixture
def sample_behavior():
    """Create a sample behavior specification for testing"""
    return BehaviorSpec(
        name="test_behavior",
        description="A test behavior for unit testing",
        capability_level="Journeyman",
        knowledge_scope="Lake",
        input_schema={
            "properties": {
                "name": {"type": "string", "description": "Name parameter"},
                "count": {"type": "integer", "description": "Count parameter"},
            },
            "required": ["name"],
        },
        output_schema={
            "properties": {
                "result": {"type": "string"},
                "status": {"type": "string"},
            }
        },
        mutates_kg=True,
        concurrency_safe=True,
        ontology_mapping="nusy:PMBehavior-Test",
        cli_example="nusy test --name example",
        sparql_query="SELECT ?x WHERE { ?x a nusy:Test }",
        source_file="test.md",
        behavior_id="test_001",
    )


class TestBehaviorSpec:
    """Test BehaviorSpec dataclass"""

    def test_behavior_spec_creation(self, sample_behavior):
        """Test creating a BehaviorSpec"""
        assert sample_behavior.name == "test_behavior"
        assert sample_behavior.capability_level == "Journeyman"
        assert sample_behavior.mutates_kg is True


class TestBDDScenario:
    """Test BDDScenario dataclass"""

    def test_scenario_creation(self):
        """Test creating a BDD scenario"""
        scenario = BDDScenario(
            scenario_name="Test scenario",
            scenario_type="happy_path",
            given_steps=["step 1", "step 2"],
            when_steps=["when action"],
            then_steps=["then result"],
            strategy_used="BottomUp",
            tags=["test"],
        )
        assert scenario.scenario_name == "Test scenario"
        assert len(scenario.given_steps) == 2
        assert scenario.strategy_used == "BottomUp"


class TestBDDFeatureFile:
    """Test BDDFeatureFile dataclass and Gherkin generation"""

    def test_feature_file_creation(self, sample_behavior):
        """Test creating a feature file"""
        scenario = BDDScenario(
            scenario_name="Test scenario",
            scenario_type="happy_path",
            given_steps=["the system is ready"],
            when_steps=["I perform action"],
            then_steps=["I see result"],
            strategy_used="BottomUp",
        )

        feature = BDDFeatureFile(
            feature_name="Test Feature",
            feature_description="A test feature",
            background_steps=["Given the system is initialized"],
            scenarios=[scenario],
            tags=["test"],
            behavior_spec=sample_behavior,
        )

        assert feature.feature_name == "Test Feature"
        assert len(feature.scenarios) == 1

    def test_gherkin_generation(self, sample_behavior):
        """Test Gherkin format generation"""
        scenario = BDDScenario(
            scenario_name="Test scenario",
            scenario_type="happy_path",
            given_steps=["the system is ready"],
            when_steps=["I perform action"],
            then_steps=["I see result"],
            strategy_used="BottomUp",
            tags=["happy-path"],
        )

        feature = BDDFeatureFile(
            feature_name="Test Feature",
            feature_description="A test feature",
            background_steps=["Given the system is initialized"],
            scenarios=[scenario],
            tags=["test"],
            behavior_spec=sample_behavior,
        )

        gherkin = feature.to_gherkin()

        # Check for key components
        assert "Feature: Test Feature" in gherkin
        assert "Background:" in gherkin
        assert "Scenario: Test scenario" in gherkin
        assert "Given the system is ready" in gherkin
        assert "When I perform action" in gherkin
        assert "Then I see result" in gherkin
        assert "@test" in gherkin
        assert "# Generated by Fishnet v2.0.0" in gherkin


class TestBottomUpStrategy:
    """Test BottomUpStrategy implementation"""

    def test_strategy_name(self):
        """Test strategy name property"""
        strategy = BottomUpStrategy()
        assert strategy.strategy_name == "BottomUp"

    def test_generate_scenarios(self, sample_behavior):
        """Test scenario generation"""
        strategy = BottomUpStrategy()
        scenarios = strategy.generate_scenarios(sample_behavior)

        # Should generate 3 scenarios
        assert len(scenarios) == 3

        # Check scenario types
        types = [s.scenario_type for s in scenarios]
        assert "happy_path" in types
        assert "edge_case" in types
        assert "error_handling" in types

        # All should be from BottomUp strategy
        for scenario in scenarios:
            assert scenario.strategy_used == "BottomUp"

    def test_happy_path_scenario(self, sample_behavior):
        """Test happy path scenario generation"""
        strategy = BottomUpStrategy()
        scenarios = strategy.generate_scenarios(sample_behavior)

        happy_path = [s for s in scenarios if s.scenario_type == "happy_path"][0]

        # Should have Given steps from input schema
        assert len(happy_path.given_steps) > 0
        assert any("knowledge graph" in step for step in happy_path.given_steps)

        # Should have When step
        assert len(happy_path.when_steps) > 0
        assert "test_behavior" in happy_path.when_steps[0]

        # Should have Then steps from output schema
        assert len(happy_path.then_steps) > 0
        assert any("succeed" in step for step in happy_path.then_steps)

    def test_edge_case_scenario(self, sample_behavior):
        """Test edge case scenario generation"""
        strategy = BottomUpStrategy()
        scenarios = strategy.generate_scenarios(sample_behavior)

        edge_case = [s for s in scenarios if s.scenario_type == "edge_case"][0]

        # Should have edge case handling steps
        assert len(edge_case.given_steps) > 0
        assert len(edge_case.when_steps) > 0
        assert len(edge_case.then_steps) > 0
        assert any("edge case" in step.lower() for step in edge_case.then_steps)

    def test_error_handling_scenario(self, sample_behavior):
        """Test error handling scenario generation"""
        strategy = BottomUpStrategy()
        scenarios = strategy.generate_scenarios(sample_behavior)

        error = [s for s in scenarios if s.scenario_type == "error_handling"][0]

        # Should have error handling assertions
        assert len(error.then_steps) > 0
        assert any("error" in step.lower() for step in error.then_steps)

    def test_generate_background(self, sample_behavior):
        """Test background step generation"""
        strategy = BottomUpStrategy()
        background = strategy._generate_background(sample_behavior)

        # Should have setup steps
        assert len(background) > 0
        assert any("MCP service" in step for step in background)
        assert any("Journeyman" in step for step in background)

    def test_generate_feature_file(self, sample_behavior):
        """Test complete feature file generation"""
        strategy = BottomUpStrategy()
        feature = strategy.generate_feature_file(sample_behavior)

        # Should have correct structure
        assert feature.feature_name == "MCP Tool: test_behavior"
        assert len(feature.scenarios) == 3
        assert len(feature.background_steps) > 0
        assert "journeyman" in feature.tags
        assert "lake" in feature.tags

    def test_mutates_kg_handling(self, sample_behavior):
        """Test handling of mutates_kg flag"""
        strategy = BottomUpStrategy()

        # Test with mutates_kg=True
        sample_behavior.mutates_kg = True
        scenarios = strategy.generate_scenarios(sample_behavior)
        happy_path = [s for s in scenarios if s.scenario_type == "happy_path"][0]
        assert any("updated" in step for step in happy_path.then_steps)

        # Test with mutates_kg=False
        sample_behavior.mutates_kg = False
        scenarios = strategy.generate_scenarios(sample_behavior)
        happy_path = [s for s in scenarios if s.scenario_type == "happy_path"][0]
        assert any("unchanged" in step for step in happy_path.then_steps)

    def test_input_schema_parsing(self, sample_behavior):
        """Test parsing of input schema for Given steps"""
        strategy = BottomUpStrategy()
        given_steps = strategy._extract_given_from_inputs(sample_behavior)

        # Should mention required parameters
        assert any("name" in step for step in given_steps)

    def test_output_schema_parsing(self, sample_behavior):
        """Test parsing of output schema for Then steps"""
        strategy = BottomUpStrategy()
        then_steps = strategy._extract_then_from_outputs(sample_behavior)

        # Should check for output fields
        assert any("result" in step or "status" in step for step in then_steps)
