# Generated by Fishnet v2.0.0
# Strategy: BottomUp
# Source: pm-behaviors-extracted.md
# Behavior: link_related_notes

@journeyman @lake @link_related_notes
Feature: MCP Tool: link_related_notes
  Create semantic relationships between notes (6 types: relatedTo, follows, references, elaborates, contradicts, supports)

  Background:
    Given the Santiago PM MCP service is running
    And the knowledge graph is initialized with test data
    And I have Journeyman level permissions

  @happy-path
  Scenario: Successfully execute link_related_notes
    Given the Santiago PM knowledge graph is initialized
    When I invoke the 'link_related_notes' MCP tool
    Then the MCP tool should succeed
    Then the knowledge graph should be updated with new data

  @edge-case
  Scenario: Handle edge cases for link_related_notes
    Given the Santiago PM knowledge graph is initialized
    Given I provide minimal valid input with no optional parameters
    When I invoke the 'link_related_notes' MCP tool with edge case data
    Then the MCP tool should handle the edge case gracefully
    Then the response should indicate any assumptions or defaults applied
    Then the knowledge graph should remain in a consistent state

  @error-handling
  Scenario: Handle errors for link_related_notes
    Given the Santiago PM knowledge graph is initialized
    Given I provide data in an invalid format
    When I invoke the 'link_related_notes' MCP tool with invalid data
    Then the MCP tool should return an error
    Then the error message should be descriptive
    Then no partial data should be committed to the knowledge graph
