# Generated by Fishnet v2.0.0
# Strategy: BottomUp
# Source: passage-behaviors-extracted.md
# Behavior: manage_passage_lifecycle

@master @sea @manage_passage_lifecycle
Feature: MCP Tool: manage_passage_lifecycle
  Transition passage through lifecycle states (draft → active → deprecated → archived), enforce governance rules

  Background:
    Given the Santiago PM MCP service is running
    And the knowledge graph is initialized with test data
    And I have Master level permissions

  @happy-path
  Scenario: Successfully execute manage_passage_lifecycle
    Given the Santiago PM knowledge graph is initialized
    When I invoke the 'manage_passage_lifecycle' MCP tool
    Then the MCP tool should succeed
    Then the knowledge graph should be updated with new data

  @edge-case
  Scenario: Handle edge cases for manage_passage_lifecycle
    Given the Santiago PM knowledge graph is initialized
    Given I provide minimal valid input with no optional parameters
    When I invoke the 'manage_passage_lifecycle' MCP tool with edge case data
    Then the MCP tool should handle the edge case gracefully
    Then the response should indicate any assumptions or defaults applied
    Then the knowledge graph should remain in a consistent state

  @error-handling
  Scenario: Handle errors for manage_passage_lifecycle
    Given the Santiago PM knowledge graph is initialized
    Given I provide data in an invalid format
    When I invoke the 'manage_passage_lifecycle' MCP tool with invalid data
    Then the MCP tool should return an error
    Then the error message should be descriptive
    Then no partial data should be committed to the knowledge graph
