# Generated by Fishnet v2.0.0
# Strategy: BottomUp
# Source: pm-behaviors-extracted.md
# Behavior: status_dashboard

@apprentice @sea @status_dashboard
Feature: MCP Tool: status_dashboard
  Visualize project status with burndown, agent productivity, feature completion metrics

  Background:
    Given the Santiago PM MCP service is running
    And the knowledge graph is initialized with test data
    And I have Apprentice level permissions

  @happy-path
  Scenario: Successfully execute status_dashboard
    Given the Santiago PM knowledge graph is initialized
    When I invoke the 'status_dashboard' MCP tool
    Then the MCP tool should succeed
    Then the knowledge graph should remain unchanged

  @edge-case
  Scenario: Handle edge cases for status_dashboard
    Given the Santiago PM knowledge graph is initialized
    Given I provide minimal valid input with no optional parameters
    When I invoke the 'status_dashboard' MCP tool with edge case data
    Then the MCP tool should handle the edge case gracefully
    Then the response should indicate any assumptions or defaults applied

  @error-handling
  Scenario: Handle errors for status_dashboard
    Given the Santiago PM knowledge graph is initialized
    Given I provide data in an invalid format
    When I invoke the 'status_dashboard' MCP tool with invalid data
    Then the MCP tool should return an error
    Then the error message should be descriptive
    Then no partial data should be committed to the knowledge graph
