# Generated by Fishnet v2.0.0
# Strategy: BottomUp, BottomUp, BottomUp
# Source: knowledge/catches/santiago-pm-behaviors/pm-behaviors-extracted.md
# Generated: 2025-11-17T05:26:58.315896

@journeyman @lake
Feature: create_note
  Capture insight, learning, or decision in captain's journal with metadata

  Background:
    the Santiago PM MCP service is running
    the knowledge graph is initialized with test data
    I have Journeyman level permissions

  @happy_path
  Scenario: Successfully execute create_note
    Given the Santiago PM knowledge graph is initialized
    When I invoke the 'create_note' MCP tool
    Then the MCP tool should succeed
    Then the knowledge graph should be updated

  @edge_case
  Scenario: Handle edge cases for create_note
    Given the Santiago PM knowledge graph is initialized
    Given I provide boundary value inputs
    When I invoke the 'create_note' MCP tool
    Then the MCP tool should handle edge cases gracefully
    Then the knowledge graph should remain consistent
    Then the response should be valid

  @error_handling
  Scenario: Handle errors for create_note
    Given the Santiago PM knowledge graph is initialized
    Given I provide invalid parameter types
    When I invoke the 'create_note' MCP tool
    Then the MCP tool should return an error
    Then the error message should be descriptive
