# Generated by Fishnet v2.0.0
# Strategy: BottomUp, BottomUp, BottomUp
# Source: knowledge/catches/santiago-pm-behaviors/pm-behaviors-extracted.md
# Generated: 2025-11-17T05:26:58.314560

@apprentice @pond
Feature: status_query
  Query artifacts by status, assignee, update date, or artifact type

  Background:
    the Santiago PM MCP service is running
    the knowledge graph is initialized with test data
    I have Apprentice level permissions

  @happy_path
  Scenario: Successfully execute status_query
    Given the Santiago PM knowledge graph is initialized
    When I invoke the 'status_query' MCP tool
    Then the MCP tool should succeed

  @edge_case
  Scenario: Handle edge cases for status_query
    Given the Santiago PM knowledge graph is initialized
    Given I provide boundary value inputs
    When I invoke the 'status_query' MCP tool
    Then the MCP tool should handle edge cases gracefully
    Then the response should be valid

  @error_handling
  Scenario: Handle errors for status_query
    Given the Santiago PM knowledge graph is initialized
    Given I provide invalid parameter types
    When I invoke the 'status_query' MCP tool
    Then the MCP tool should return an error
    Then the error message should be descriptive
